# config/default.yaml

paths:
  raw_data:           data/raw
  consolidated_data:  data/consolidated
  processed_data:     data/processed
  input_data:         data/input
  output_data:        data/output
  archive:            data/archive

models:
  output_format: csv
  tournaments: null

scraper:
  tournament_ids:
    - XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
