# src/constants.py

from enum import Enum

#------------------------------------------------------------

class StrEnum(str, Enum):
    """
    Base class for string enums to allow for type checking and autocompletion.
    """
    def __str__(self):
        return self.value
    
    def __repr__(self):
        return self.value
    
#-------------------------------------------------------------------------

class FileNames:
    """
    Class for standard file names used in the pipeline.
    """
    class Input(StrEnum):
        """
        Standard file names for input files (not generated by the pipeline)
        """
        PLAYERS = 'players.json'
        PLAYER_ID_MAP = 'player_id_map.json'


    class Raw(StrEnum):
        """
        Standard file names for raw data files (output of scraping, input to parsing)
        """
        METADATA = 'metadata.json'


    class Flat(StrEnum):
        """
        Standard file names for flat data files (output of consolidation)
        """
        TOURNAMENTS = "tournaments.json"
        MATCHES = "matches.json"
        PLAYERS = "players.json"

#-------------------------------------------------------------------------

class DataKeys:
    """
    Class for standard data keys used in the pipeline.
    """
    class Tournament(StrEnum):
        """
        Standard keys for tournament records
        """
        ID = "tournament_id"
        NAME = "tournament_name"
        START_DATE = "start_date"
        END_DATE = "end_date"
        DURATION_DAYS = "duration_days"
        NUM_GAME_DAYS = "num_game_days"
        IS_ACTIVE = "is_active"
        NUM_CATEGORIES = "num_categories"
        NUM_POULES = "num_poules"
        NUM_REGISTRATIONS = "num_registrations"
        NUM_PLAYERS = "num_players"
        NUM_MATCHES = "num_matches"
        NUM_MATCHES_PLAYED = "num_matches_played"
        COMPLETION_RATE = "completion_rate"
        AVG_MATCHES_PER_PLAYER = "avg_matches_per_player"
        AVG_MATCHES_PER_POULE = "avg_matches_per_poule"
        IS_COMPLETED = "is_completed"


    class Match(StrEnum):
        """
        Standard keys for match records
        """
        ID = "match_id"
        CATEGORY = "category"
        POULE = "poule"
        DATE = "date"
        TIME = "time"
        TEAM_1 = "team_1"
        TEAM_2 = "team_2"
        WINNER = "winner_team"
        WINNER_SCORE = "winner_score"
        LOSER_SCORE= "loser_score"
        SCORE_DIFF = "score_diff"
        IS_PLAYED = "is_played"
        IS_WALKOVER = "is_walkover"
        IS_VALID = "is_valid"
        STATUS = "status"
        INFO = "info"


    class Team(StrEnum):
        """
        Standard keys for team records
        """
        PLAYER_1 = "player_1"
        PLAYER_2 = "player_2"
        SCORE = "score"
        WINNER = "winner"


    class Player(StrEnum):
        """
        Standard keys for player records
        """
        ID = "id"
        NAME = "name"
        FIRST_SEEN = "first_seen"
        LAST_SEEN = "last_seen"
        ACTIVE_SPAN_DAYS = "active_span_days"
        NUM_MATCHES = "num_matches"
        NUM_MATCHES_PLAYED = "num_matches_played"
        NUM_WINS = "num_wins"
        NUM_LOSSES = "num_losses"
        WIN_RATE = "win_rate"
        LOSS_RATE = "loss_rate"
        NUM_GAMES_WON = "num_games_won"
        NUM_GAMES_LOST = "num_games_lost"
        GAMES_WIN_RATE = "games_win_rate"
        PERFORMANCE_INDEX = "performance_index"
        PARTNERS = "partners"


    class Rating(StrEnum):
        """
        Standard keys for player rating records
        """
        INITIAL_RANK = "initial_rank"
        ELO_VALUE = "elo_value"
        SKILL_MU = "skill_mu"
        SKILL_SIGMA = "skill_sigma"
        ELO_RANK = "elo_rank"
        KNLTB_RANK = "knltb_rank"
        TRUESKILL_RANK = "trueskill_rank"


    class General(StrEnum):
        """
        General keys used across multiple record types
        """
        SCRAPED_AT = "scraped_at"

#-------------------------------------------------------------------------

class DefaultValues:
    """
    Class for default values used in the pipeline.
    """
    class Entries(StrEnum):
        """
        Default values for various data entries
        """
        POULE_PLACEHOLDER = "X"
        COMPLETED_STATUS = "completed"
        PENDING_STATUS = "pending"
        CANCELED_MATCH_INFO = "Geannuleerd"
        WALKOVER_VALUES = ["Walkover", "Opgave", "Diskwalificatie"]


    class DateFormat(StrEnum):
        """
        Default date and time formats
        """
        DATE = r"%Y-%m-%d"
        TIME = r"%H:%M:%S"
        DATETIME = DATE + " " + TIME
