# src/constants.py

from enum import Enum

#------------------------------------------------------------

class StrEnum(str, Enum):
    """
    Base class for string enums to allow for type checking and autocompletion.
    """
    def __str__(self):
        return self.value
    
    def __repr__(self):
        return self.value
    

class FloatEnum(float, Enum):
    """
    Base class for float enums to ellow for type checking and autocompletion.
    """
    def __repr__(self):
        return self.value
    
#-------------------------------------------------------------------------

class FileNames:
    """
    Class for standard file names used in the pipeline.
    """
    class Input(StrEnum):
        """
        Standard file names for input files (not generated by the pipeline)
        """
        PLAYERS         = 'players.json'
        PLAYER_ID_MAP   = 'player_id_map.json'


    class Raw(StrEnum):
        """
        Standard file names for raw data files (output of scraping, input to parsing)
        """
        METADATA = 'metadata.json'


    class Flat(StrEnum):
        """
        Standard file names for flat data files (output of consolidation)
        """
        TOURNAMENTS = "tournaments.json"
        MATCHES     = "matches.json"
        PLAYERS     = "players.json"
        TEAMS       = "teams.json"

#-------------------------------------------------------------------------

class DataKeys:
    """
    Class for standard data keys used in the pipeline.
    """
    class Tournament(StrEnum):
        """
        Standard keys for tournament records
        """
        ID                     = "id"
        NAME                   = "name"
        START_DATE             = "start_date"
        END_DATE               = "end_date"
        DURATION_DAYS          = "duration_days"
        NUM_GAME_DAYS          = "num_game_days"
        IS_ACTIVE              = "is_active"
        NUM_CATEGORIES         = "num_categories"
        NUM_POULES             = "num_poules"
        NUM_REGISTRATIONS      = "num_registrations"
        NUM_PLAYERS            = "num_players"
        NUM_MATCHES            = "num_matches"
        NUM_MATCHES_PLAYED     = "num_matches_played"
        COMPLETION_RATE        = "completion_rate"
        AVG_MATCHES_PER_PLAYER = "avg_matches_per_player"
        AVG_MATCHES_PER_POULE  = "avg_matches_per_poule"
        IS_COMPLETED           = "is_completed"


    class Match(StrEnum):
        """
        Standard keys for match records
        """
        ID           = "id"
        TOURNAMENT   = "tournament"
        CATEGORY     = "category"
        POULE        = "poule"
        DATE         = "date"
        TIME         = "time"
        TEAM_1_ID    = "team_1_id"
        TEAM_2_ID    = "team_2_id"
        TEAM_1_SCORE = "team_1_score"
        TEAM_2_SCORE = "team_2_score"
        WINNER       = "winner_team"
        WINNER_SCORE = "winner_score"
        LOSER_SCORE  = "loser_score"
        SCORE_DIFF   = "score_diff"
        TOTAL_GAMES  = "total_games"
        IS_PLAYED    = "is_played"
        IS_WALKOVER  = "is_walkover"
        IS_VALID     = "is_valid"
        STATUS       = "status"
        INFO         = "info"


    class Team(StrEnum):
        """
        Standard keys for team records
        """
        ID       = "id"
        PLAYER_1 = "player_1"
        PLAYER_2 = "player_2"
        SCORE    = "score"
        WINNER   = "winner"


    class Player(StrEnum):
        """
        Standard keys for player records
        """
        ID                  = "id"
        NAME                = "name"
        GENDER              = "gender"
        FIRST_SEEN          = "first_seen"
        LAST_SEEN           = "last_seen"
        ACTIVE_SPAN_DAYS    = "active_span_days"
        NUM_MATCHES         = "num_matches"
        NUM_MATCHES_PLAYED  = "num_matches_played"
        NUM_WINS            = "num_wins"
        NUM_LOSSES          = "num_losses"
        WIN_RATE            = "win_rate"
        LOSS_RATE           = "loss_rate"
        NUM_GAMES_WON       = "num_games_won"
        NUM_GAMES_LOST      = "num_games_lost"
        GAMES_WIN_RATE      = "games_win_rate"
        PERFORMANCE_INDEX   = "performance_index"
        PARTNERS            = "partners"


    class Rating(StrEnum):
        """
        Standard keys for player rating records
        """
        INITIAL_RANK            = "initial_rank"
        ELO_VALUE               = "elo_value"
        SKILL_MU                = "skill_mu"
        SKILL_SIGMA             = "skill_sigma"
        ELO_RANK                = "elo_rank"
        KNLTB_RANK              = "knltb_rank"
        TRUESKILL_RANK          = "trueskill_rank"
        ADJUSTED_TRUESKILL_RANK = "adjusted_trueskill_rank"


    class General(StrEnum):
        """
        General keys used across multiple record types
        """
        SCRAPED_AT = "scraped_at"

#-------------------------------------------------------------------------

class DefaultValues:
    """
    Class for default values used in the pipeline.
    """
    class Match:
        """
        Class for default values used in match records.
        """
        class Status(StrEnum):
            COMPLETED   = "completed"
            PENDING     = "pending"

        class Info(StrEnum):
            CANCELED    = "Geannuleerd"

        WALKOVER_VALUES = ["Walkover", "Opgave", "Diskwalificatie"]


    class Entries(StrEnum):
        """
        Default values for various data entries
        """
        POULE_PLACEHOLDER   = "X"
        UNKNOWN             = "unknown"


    class DateFormat(StrEnum):
        """
        Default date and time formats
        """
        DATE        = r"%Y-%m-%d"
        TIME        = r"%H:%M:%S"
        DATETIME    = DATE + " " + TIME

    
    class Models:
        """
        Class for default values used as model parameters
        """
        class Knltb(FloatEnum):
            """
            Default KnltbModel parameters
            """
            K       = 0.275
            Q       = 2.012
            THETA   = 0.5
            R0      = 8.0


        class TrueSkill(FloatEnum):
            """
            Default TrueSkillModel parameters
            """
            SIGMA0      = 9.0
            BETA        = 4.5
            DRAW_PROB   = 0.05
            R0          = 8.0

        
        class Conversion(FloatEnum):
            """
            Default parameters for converting between ratings
            """
            KNLTB_MIN   = 1.0
            KNLTB_MAX   = 9.0
            MU_MIN      = 10.0
            MU_MAX      = 40.0
